#!/usr/bin/env python3
"""
Regenerates the single-file bundles from the shared source in desktop/.

It embeds the ZLTRouterClient (desktop/router_client.py) plus the web UI
(desktop/static/*) as base64 into a self-contained Python server, and writes:

  * mobile/airtel_monitor.py                 (binds 0.0.0.0 - Termux / desktop)
  * app/src/main/python/airtel_monitor.py    (binds 127.0.0.1 - Android/Chaquopy)

Run from the repo root:  python tools/build_mobile.py
"""
import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DESKTOP = os.path.join(ROOT, "desktop")
ANDROID_PY = os.path.join(ROOT, "app", "src", "main", "python", "airtel_monitor.py")
MOBILE_PY = os.path.join(ROOT, "mobile", "airtel_monitor.py")


def b64(path):
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode("ascii")


def build():
    rc = open(os.path.join(DESKTOP, "router_client.py"), encoding="utf-8").read()
    client_src = rc[rc.index("class ZLTRouterClient"):]

    assets = {
        "index.html": b64(os.path.join(DESKTOP, "static", "index.html")),
        "css/style.css": b64(os.path.join(DESKTOP, "static", "css", "style.css")),
        "js/app.js": b64(os.path.join(DESKTOP, "static", "js", "app.js")),
    }

    header = '''#!/usr/bin/env python3
"""
Airtel 5G Router Monitor - SINGLE-FILE EDITION (generated by tools/build_mobile.py)
Runs the whole app from one file. Phone must be on the router's Wi-Fi.
Zero external dependencies - Python standard library only.
"""
import http.server
import json
import os
import base64
import threading
import time
import urllib.parse
import urllib.request
import hashlib
import uuid
from typing import Dict, List, Any, Optional

PORT = 8080

'''

    server_src = '''

# ------------------------- Embedded UI assets -------------------------
_ASSETS_B64 = __ASSETS__
_CONTENT_TYPES = {
    "index.html": "text/html; charset=utf-8",
    "css/style.css": "text/css; charset=utf-8",
    "js/app.js": "application/javascript; charset=utf-8",
}

client = ZLTRouterClient(host="192.168.1.1", username="root", password="admin")
is_running = True
poll_interval = 2.0


def background_poller():
    global is_running
    print("[Poller] Connecting to router at 192.168.1.1 ...")
    if client.login():
        print("[Poller] Authenticated with Airtel ZLT router.")
    else:
        print("[Poller] Login failed; will retry in the background loop.")
    while is_running:
        try:
            client.poll_metrics()
        except Exception as e:
            print(f"[Poller Error] {e}")
        time.sleep(poll_interval)


class MonitorHandler(http.server.BaseHTTPRequestHandler):
    def _send(self, body: bytes, ctype: str, status: int = 200):
        self.send_response(status)
        self.send_header("Content-Type", ctype)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Cache-Control", "no-cache, no-store")
        self.end_headers()
        self.wfile.write(body)

    def _json(self, data: dict, status: int = 200):
        self._send(json.dumps(data).encode("utf-8"), "application/json", status)

    def _asset(self, key: str):
        raw = base64.b64decode(_ASSETS_B64[key])
        self._send(raw, _CONTENT_TYPES[key])

    def do_GET(self):
        path = urllib.parse.urlparse(self.path).path
        if path == "/api/status":
            self._json(client.cached_state or client.poll_metrics()); return
        if path == "/api/config":
            self._json({"router_host": client.host, "poll_interval": poll_interval,
                        "custom_aliases": client.custom_aliases}); return
        if path == "/api/dns":
            self._json(client.get_dns()); return
        key ="index.html" if path in ("/", "/index.html") else path.lstrip("/")
        if key in _ASSETS_B64:
            self._asset(key); return
        self._send(b"Not found", "text/plain", 404)

    def do_POST(self):
        path = urllib.parse.urlparse(self.path).path
        n = int(self.headers.get("Content-Length", 0))
        try:
            body = json.loads(self.rfile.read(n).decode("utf-8")) if n else {}
        except Exception:
            body = {}
        if path == "/api/alias":
            ident = body.get("identifier")
            if not ident:
                self._json({"success": False, "error": "Missing identifier"}, 400); return
            client.save_alias(ident, body.get("alias", "").strip())
            client.poll_metrics()
            self._json({"success": True}); return
        if path == "/api/reboot":
            if body.get("confirm") is not True:
                self._json({"success": False, "error": "Missing confirm:true"}, 400); return
            self._json({"success": client.reboot()}); return
        if path == "/api/dns":
            if body.get("confirm") is not True:
                self._json({"success": False, "error": "Missing confirm:true"}, 400); return
            self._json(client.set_dns(body.get("primary", ""), body.get("secondary", ""))); return
        if path == "/api/set-interval":
            global poll_interval
            poll_interval = max(1.0, min(10.0, float(body.get("interval", 2.0))))
            self._json({"success": True, "interval": poll_interval}); return
        self._json({"error": "Endpoint not found"}, 404)

    def log_message(self, fmt, *args):
        pass  # quiet on mobile


def main():
    threading.Thread(target=background_poller, daemon=True).start()
    httpd = http.server.ThreadingHTTPServer((__BIND__, PORT), MonitorHandler)
    print("\\n=======================================================")
    print("  Airtel 5G Router Monitor - Mobile Edition")
    print(f"  Open your phone browser at:  http://localhost:{PORT}")
    print("  (keep this app open while you use the dashboard)")
    print("=======================================================\\n")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        global is_running
        is_running = False
        httpd.server_close()


if __name__ == "__main__":
    main()
'''

    body = header + client_src.rstrip() + "\n" + server_src.replace("__ASSETS__", repr(assets))

    # Termux / desktop variant: listen on all interfaces.
    with open(MOBILE_PY, "w", encoding="utf-8") as f:
        f.write(body.replace("__BIND__", '""'))
    # Android / Chaquopy variant: loopback only (WebView reads localhost).
    with open(ANDROID_PY, "w", encoding="utf-8") as f:
        f.write(body.replace("__BIND__", '"127.0.0.1"'))

    print("Wrote:")
    print("  ", MOBILE_PY)
    print("  ", ANDROID_PY)


if __name__ == "__main__":
    build()
